import{computeCameraTarget}from'../camera/stageCamera';import{MatterStore}from'../matter/matterStore';import type{EntityId,MatterSnapshot,StageId}from'../matter/matterTypes';import{DEFAULT_SPIRAL}from'./stageLayout';import type{CompressionPhase,StageDefinition,StageTransfer}from'./stageTypes';
export interface StageConfig{schemaVersion:1;stage2UnlockLifetimeSand:number;compressionInputCount:number;reservoirCapacity:number;transferDuration:number;timings:Record<Exclude<CompressionPhase,'gathering'|'ready'>,number>}
export const DEFAULT_STAGE_CONFIG:StageConfig={schemaVersion:1,stage2UnlockLifetimeSand:100,compressionInputCount:100,reservoirCapacity:300,transferDuration:.65,timings:{levitating:.8,aligning:.65,compressing:.45,impact:.12,revealing:.65,releasing:.7,cooldown:.25}};
export const STAGES:StageDefinition[]=DEFAULT_SPIRAL.map((gridPosition,i)=>({id:(i===0?'sandfall-atrium':i===1?'compression-crucible':`stage-${i+1}`)as StageId,order:i+1,name:i===0?'Sandfall Atrium':i===1?'Compression Crucible':`Stage ${i+1}`,gridPosition,inputMaterial:i===0?null:i===1?'sand':'stone',outputMaterial:i===0?'sand':'stone',implemented:i<2,unlockCondition:i===0?{kind:'initial'}:{kind:'lifetime-material',stageId:'sandfall-atrium',material:'sand',count:i===1?100:Number.MAX_SAFE_INTEGER},connectionTargets:i===0?['compression-crucible']:[]}));
export interface StageSave{version:1;unlocked:StageId[];lifetimeSand:number;processedSand:number;phase:CompressionPhase;phaseTime:number;ritualIds:EntityId[];outputStoneIds:EntityId[];transfers:StageTransfer[];matter:MatterSnapshot}
export class StageController{readonly matter=new MatterStore();readonly definitions=STAGES;unlocked=new Set<StageId>(['sandfall-atrium']);lifetimeSand=0;processedSand=0;phase:CompressionPhase='gathering';phaseTime=0;ritualIds:EntityId[]=[];outputStoneIds:EntityId[]=[];transfers:StageTransfer[]=[];conversionEvents=0;private transferSerial=0;private converted=false;constructor(public config:StageConfig=DEFAULT_STAGE_CONFIG){}
 castSand(count=1){for(let i=0;i<count;i++){const e=this.matter.create('sand',{kind:'stage',stageId:'sandfall-atrium',slot:'active'},'sandfall-atrium',{x:12+((this.lifetimeSand*17)%24),y:2});this.lifetimeSand++;e.vy=4}this.checkUnlock()}
 private checkUnlock(){if(this.lifetimeSand>=this.config.stage2UnlockLifetimeSand)this.unlocked.add('compression-crucible')}
 queueStage1Sand(id:EntityId){const e=this.matter.get(id);if(e.owner.kind!=='stage'||e.owner.stageId!=='sandfall-atrium')throw Error('Sand is not in Stage 1');this.matter.move(id,{kind:'stage',stageId:'sandfall-atrium',slot:'output'})}
 beginTransfer(id:EntityId){if(!this.unlocked.has('compression-crucible'))return false;if(this.reservoir().length+this.transfers.length>=this.config.reservoirCapacity)return false;const e=this.matter.get(id);if(e.owner.kind!=='stage'||e.owner.stageId!=='sandfall-atrium'||e.owner.slot!=='output')return false;const transferId=`s1-s2-${++this.transferSerial}`;this.matter.move(id,{kind:'transfer',transferId});this.transfers.push({id:transferId,entityId:id,connectionId:'stage-1-to-2',progress:0});return true}
 update(dt:number){dt=Math.max(0,Math.min(dt,.1));for(const t of this.transfers)t.progress+=dt/this.config.transferDuration;const done=this.transfers.filter(t=>t.progress>=1);this.transfers=this.transfers.filter(t=>t.progress<1);for(const t of done)this.matter.move(t.entityId,{kind:'stage',stageId:'compression-crucible',slot:'reservoir'});if(this.phase==='gathering'&&this.reservoir().length>=this.config.compressionInputCount)this.phase='ready';if(this.phase!=='gathering'&&this.phase!=='ready'){this.phaseTime+=dt;const duration=this.config.timings[this.phase];if(this.phaseTime>=duration)this.advancePhase()}this.matter.assertInvariants()}
 invokeRitual(){if(this.phase!=='ready'||this.reservoir().length<this.config.compressionInputCount)return false;this.ritualIds=this.reservoir().slice(0,this.config.compressionInputCount).map(e=>e.id);this.ritualIds.forEach(id=>this.matter.move(id,{kind:'stage',stageId:'compression-crucible',slot:'ritual'}));this.phase='levitating';this.phaseTime=0;this.converted=false;return true}
 private advancePhase(){this.phaseTime=0;const order:CompressionPhase[]=['levitating','aligning','compressing','impact','revealing','releasing','cooldown','gathering'];const next=order[order.indexOf(this.phase)+1]??'gathering';if(this.phase==='impact')this.convertOnce();if(this.phase==='cooldown'){this.ritualIds=[];this.converted=false}this.phase=next;if(this.phase==='gathering'&&this.reservoir().length>=this.config.compressionInputCount)this.phase='ready'}
 private convertOnce(){if(this.converted)return;this.converted=true;const stone=this.matter.compose('stone',this.ritualIds,{kind:'stage',stageId:'compression-crucible',slot:'output'},'compression-crucible');this.outputStoneIds.push(stone.id);this.processedSand+=this.ritualIds.length;this.conversionEvents++}
 reservoir(){return this.matter.owned((o,e)=>e.material==='sand'&&o.kind==='stage'&&o.stageId==='compression-crucible'&&o.slot==='reservoir')}
 cameraTarget(){return computeCameraTarget(this.definitions.filter(d=>this.unlocked.has(d.id)).map(d=>d.gridPosition))}
 serialize():StageSave{return{version:1,unlocked:[...this.unlocked],lifetimeSand:this.lifetimeSand,processedSand:this.processedSand,phase:this.phase,phaseTime:this.phaseTime,ritualIds:[...this.ritualIds],outputStoneIds:[...this.outputStoneIds],transfers:this.transfers.map(t=>({...t})),matter:this.matter.serialize()}}
 hydrate(s:StageSave){this.matter.hydrate(s.matter);this.unlocked=new Set(s.unlocked.filter(id=>this.definitions.some(d=>d.id===id&&d.implemented)));this.unlocked.add('sandfall-atrium');this.lifetimeSand=s.lifetimeSand;this.processedSand=s.processedSand;this.outputStoneIds=[...s.outputStoneIds];this.transfers=s.transfers.map(t=>({...t}));this.ritualIds=[...s.ritualIds];if(s.phase!=='gathering'&&s.phase!=='ready'){for(const id of this.ritualIds){const e=this.matter.get(id);if(e.owner.kind==='stage'&&e.owner.slot==='ritual')this.matter.move(id,{kind:'stage',stageId:'compression-crucible',slot:'reservoir'})}this.ritualIds=[];this.phase=this.reservoir().length>=this.config.compressionInputCount?'ready':'gathering';this.phaseTime=0}else{this.phase=s.phase;this.phaseTime=s.phaseTime}this.matter.assertInvariants()}
}
